#!/bin/sh

app_root=${APPDIR:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)}
export MOZ_APP_LAUNCHER=${APPIMAGE:-${app_root}/AppRun}
export WILDBUZZARD_BROWSER_BINARY="${app_root}/usr/lib/wildbuzzard/wildbuzzard"
exec "${app_root}/usr/bin/wildbuzzard-native-client" "$@"
