# SPDX-License-Identifier: AGPL-3.0-or-later

Classes = [
    {
        'cid': '{75897cdd-45d8-4d8c-872f-1b603fb55d9a}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=torrents'],
        'esModule': 'resource:///modules/AboutTorrents.sys.mjs',
        'constructor': 'AboutTorrents',
    },
    {
        'cid': '{1c629541-bb57-4435-aacd-edb806f7a4e7}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=moz-torrent'],
        'esModule': 'resource:///modules/QBittorrentProtocolHandler.sys.mjs',
        'constructor': 'QBittorrentProtocolHandler',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'protocol_config': {
            'scheme': 'moz-torrent',
            'flags': [
                'URI_STD',
                'URI_DANGEROUS_TO_LOAD',
                'URI_IS_LOCAL_RESOURCE',
                'URI_IS_POTENTIALLY_TRUSTWORTHY',
                'URI_IS_UI_RESOURCE',
                'URI_NOAUTH',
                'URI_NON_PERSISTABLE',
            ],
        },
    },
    {
        'cid': '{3c20a697-9508-4c7e-a00c-f0ca555a8c95}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=magnet'],
        'esModule': 'resource:///modules/MagnetProtocolHandler.sys.mjs',
        'constructor': 'MagnetProtocolHandler',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'protocol_config': {
            'scheme': 'magnet',
            'flags': [
                'URI_LOADABLE_BY_ANYONE',
                'URI_NON_PERSISTABLE',
                'URI_NORELATIVE',
                'URI_NOAUTH',
            ],
        },
    },
    {
        'cid': '{a4241547-2440-441b-99a0-cd278ef88fdd}',
        'contract_ids': [
            '@mozilla.org/uriloader/content-handler;1?type=application/x-bittorrent',
            '@mozilla.org/uriloader/content-handler;1?type=application/vnd.bittorrent',
        ],
        'esModule': 'resource:///modules/TorrentContentHandler.sys.mjs',
        'constructor': 'TorrentContentHandler',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
