/* SPDX-License-Identifier: AGPL-3.0-or-later */

// Generated by wildbuzzard/scripts/generate-torrent-document-sources.py.
// Hashes cover pinned source and English fallback with CACHEID set to 0.
export const TORRENT_DOCUMENT_SOURCES = {
  "/addpeers.html": {
    inline: [
      "rrBJYd0nqtlUWtDQ7Rwhq8JZdTMWdkJWwNfyqUv4qo0=",
      "tQWQU7DedkqxD7qR5ilXlLbMlHjkzRkvrO9jZyz7mOw=",
    ],
    handlers: ["HTmcIylnIldABaIvUCVx0YMyAFTrpqnXF693q6GN++Y="],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/addtorrent.html": {
    inline: ["520MqDzdGUkt1/4FaOGLLpPRUDShnegaw3EVnNK0Hdo="],
    handlers: [
      "GbjNecF7Y2yl6DjWHMj1w6t4b8e08yd1FTNXOmsN8MM=",
      "JqOXnCV9B5zrPshhXCVphjO+yleYG/2s3+q5y2SkrRc=",
    ],
    external: [
      "/scripts/addtorrent.js",
      "/scripts/color-scheme.js",
      "/scripts/contextmenu.js",
      "/scripts/dynamicTable.js",
      "/scripts/file-tree.js",
      "/scripts/filesystem.js",
      "/scripts/lib/MooTools-Core-1.6.0-compat-compressed.js",
      "/scripts/lib/MooTools-More-1.6.0-compat-compressed.js",
      "/scripts/lib/vanillaSelectBox.js",
      "/scripts/localpreferences.js",
      "/scripts/misc.js",
      "/scripts/pathAutofill.js",
      "/scripts/torrent-content.js",
    ],
  },
  "/addtrackers.html": {
    inline: ["bkouwqTs1VnhTG1TSQhuCMOOl4d3nG0iwBAjgFXTbP4="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/addwebseeds.html": {
    inline: ["8K4HBEMWtlDh8K6zpgNRJPzaCZwPfLTnvdLyX3wRxHg="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/confirmfeeddeletion.html": {
    inline: ["qC1uO11iuNO0Kh66oNc5xUZGwEIVNRHDAemcgMvow68="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/confirmruleclear.html": {
    inline: ["5Gz3XEOaNZmj0uhz/wzAObq+wttrOf+xYoYV8fF5N5s="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/confirmruledeletion.html": {
    inline: ["ZbkrkXnFRG56fPICC4062s9C3jhiUBP9monv4RRGORs="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/confirmtrackerdeletion.html": {
    inline: [
      "IiCy86JBZuut/H/5ENWwlE+kY4FGibEJIBVSpn98zI0=",
      "Okx0WpzOrduV3DuK2pk+RMJLN1xRfOwojvsFSL6nhKI=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/download.html": {
    inline: [
      "92CnKlPNB9BuAC/2826DMLWnDjL8CCa3F87Smr964ag=",
      "I29dEO+O8z0ZlByHI7+uQT9mPPYiBhJozuYZ7kUP7o4=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/editfeedurl.html": {
    inline: [
      "aRUjK6aEK5RUGsms6T/Rb8uT4xW4uLsbc7LKZn0Brwg=",
      "grsPoZQs56kVPxDpFa+GKE9lRHfpoigVZ3RAJWytIdU=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/edittracker.html": {
    inline: ["eRz3H96IOI7sBtOI//xOuiyey4n965XUVSNTb2PP9eI="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/editwebseed.html": {
    inline: ["2wEyh8MXonUbt4nbg3yM+GIaI+3T2nxKdojuDu2uV7Q="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/index.html": {
    inline: [],
    handlers: [],
    external: [
      "/scripts/cache.js",
      "/scripts/client-data.js",
      "/scripts/client.js",
      "/scripts/color-scheme.js",
      "/scripts/contextmenu.js",
      "/scripts/dynamicTable.js",
      "/scripts/file-tree.js",
      "/scripts/filesystem.js",
      "/scripts/lib/MooTools-Core-1.6.0-compat-compressed.js",
      "/scripts/lib/MooTools-More-1.6.0-compat-compressed.js",
      "/scripts/lib/clipboard-copy.js",
      "/scripts/lib/mocha.min.js",
      "/scripts/localpreferences.js",
      "/scripts/misc.js",
      "/scripts/mocha-init.js",
      "/scripts/monkeypatch.js",
      "/scripts/pathAutofill.js",
      "/scripts/piecesbar.js",
      "/scripts/progressbar.js",
      "/scripts/rename-files.js",
      "/scripts/statistics.js",
      "/scripts/torrent-content.js",
      "/scripts/wildbuzzard-bridge.js",
    ],
  },
  "/newcategory.html": {
    inline: [
      "4P6/fjGKGOfhUFr3tNe9/vImpEBS4MOmWZd/H/ehOjY=",
      "HMqF+ztqCf8PJvLFeIvwF2gYPYB1hv3nlM32wnw0Ab8=",
    ],
    handlers: [],
    external: [
      "/scripts/color-scheme.js",
      "/scripts/localpreferences.js",
      "/scripts/misc.js",
      "/scripts/pathAutofill.js",
    ],
  },
  "/newfeed.html": {
    inline: [
      "E5DYdkXUfzScJTqBoglcAQFc7siuD3eLTTfzWxv+6gI=",
      "vvsVoO0K5GoieIcJeSs369Lvx8CKHyQoPnc06vyUpTc=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/newfolder.html": {
    inline: [
      "DegwVPWkR6oB6LwGAlpy16OKNUpeoc36HXkj0EVGT8w=",
      "y7yudFThWm/VLtsr/7ZKsS94nnltaDjiHMrAkyq+bnc=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/newrule.html": {
    inline: [
      "+LYN+G00S4FfJ82bZGqQN8AEqJ/TjGn/vBneDHgaUGM=",
      "VePWrhOwjv+99n2UfvbpiToQgHHVykBA/kspC4WcnrU=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/newtag.html": {
    inline: [
      "D7LESDBQYAyRKLQ+jvZ5SGhAnhUpccOnR151T6FCkXs=",
      "YBwXEi+XK0JKbdxeTEFX12Xzv6R4n3jxcPeDnQ158Hg=",
    ],
    handlers: [],
    external: [
      "/scripts/color-scheme.js",
      "/scripts/localpreferences.js",
      "/scripts/misc.js",
    ],
  },
  "/rename.html": {
    inline: ["5G9DjpJmZ3eo4C3lhiIW3s9f7WQ4qUtPr2nWuJ2fgLE="],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/rename_feed.html": {
    inline: [
      "+sK42bJcrnnic+wTHmRVnfsUTqew/QAGHT6YDIw2KB0=",
      "SV+Ix7rCy8mkMh+mq1RLoRaznmNeIgssciguJNgoVVE=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/rename_file.html": {
    inline: [
      "9K4icjojFzPKoClnDOBhGvhTUbmTUiv2LAMhzRemYDQ=",
      "SsjM5yABJHQ4i4/8OnySHrHwRgx2RTaDeem5C+upg2k=",
    ],
    handlers: [],
    external: [
      "/scripts/color-scheme.js",
      "/scripts/filesystem.js",
      "/scripts/localpreferences.js",
    ],
  },
  "/rename_files.html": {
    inline: [
      "96f7ulb5eHr2Pb4222Xel04VtfHZ1YJSoNBfxyYlKa4=",
      "mS0mEy7CAjZgV9+0LxF2Wgr0Nvo94rnjS51el/bVXN0=",
    ],
    handlers: ["xUcJaU0hSnqCscq0QL6rFlCgsV7hQhosMbqswFugUAg="],
    external: [
      "/scripts/dynamicTable.js",
      "/scripts/file-tree.js",
      "/scripts/filesystem.js",
      "/scripts/misc.js",
      "/scripts/rename-files.js",
    ],
  },
  "/rename_rule.html": {
    inline: [
      "UVL1OwfE1UMCUTMoox1JvoS9I1F/riFkp9Q/YINTTRI=",
      "lRj/8EZij7LMTcwambyhC0+a5zf1gqjA4HYIC6lz/8A=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/setlocation.html": {
    inline: [
      "S5xMrEPh5vzK40esKzIImCLBcgY+rwjqHWWAitcRKx8=",
      "foWL5ybAIkTpfBFDCRY1bDWdptZelzBphnAgbsvdkU4=",
    ],
    handlers: [],
    external: [
      "/scripts/color-scheme.js",
      "/scripts/localpreferences.js",
      "/scripts/pathAutofill.js",
    ],
  },
  "/shareratio.html": {
    inline: ["1kyXEyMyfzfpTZqNfA/6vONNmnowos6r2TrxEaKRq10="],
    handlers: [
      "L4vh8KLodT8f7R3snIwoywMQmGBeQDqmlZt6JVPIJ3k=",
      "S1g2zwzybbwlyREFVqZiYBiVoVwYPOjMTDvlImWwM14=",
    ],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/speedlimit.html": {
    inline: [
      "J3XIZL/WOdlpG0eZgYkctrc5eohr/IY8PljBl5aswBQ=",
      "JCLvVjB/qnhunvYnqSRDCd8zpP6ThbQ4R4GFhWSpDRE=",
    ],
    handlers: [],
    external: ["/scripts/color-scheme.js", "/scripts/localpreferences.js"],
  },
  "/views/about.html": {
    inline: [
      "7QXsJz0ifDvpmMcxSKAr6ih5KCp4Ojj6N4VoxUNaN4k=",
      "xLCf1De7nPbsDbQaW1FPqEfAEUumYE8Gys2G/6XVo8c=",
    ],
    handlers: [],
    external: [],
  },
  "/views/aboutToolbar.html": {
    inline: ["ICdpL0/8gxvj/1UZJUFy3VLp+mTbd1I92ZQQqCTdBIM="],
    handlers: [],
    external: [],
  },
  "/views/confirmAPIKey.html": {
    inline: ["AhFEn347Ty81HV4uA8qlhHVd6Oviy8wdXgtv8kZnwJk="],
    handlers: [],
    external: [],
  },
  "/views/confirmAutoTMM.html": {
    inline: [
      "USXM76rS2Yv2iOuZ9HXDg3lZpAghV8v6e1iTOZt9JeU=",
      "X1diVplzeO3dSHWYiajutpPFB80ng0GvHsuW2Hah+Zw=",
    ],
    handlers: [],
    external: [],
  },
  "/views/confirmRecheck.html": {
    inline: [
      "3iw7e+7lZTwFhkyX8jEwbPRRsDOGYzxaWgXolgBZ0fo=",
      "qcymLKeX2VdZmtb0mrz6tMTmOrvThUOtbvAO4Xpd1WQ=",
    ],
    handlers: [],
    external: [],
  },
  "/views/confirmdeletion.html": {
    inline: [
      "Pc+Y4y2UxMiNHWQIjkoSGuB/LHUzbWNvbCaADPlNer8=",
      "WNk7WxXYaNFiwZ8s7KAUQe5sxfAePHMDmNQ5MpNfUkY=",
    ],
    handlers: [],
    external: [],
  },
  "/views/cookies.html": {
    inline: ["emBingYfijWPy6IUJpOIAf/1eogbnfYQXudSUotDlMs="],
    handlers: [],
    external: [],
  },
  "/views/createtorrent.html": {
    inline: [
      "aAgWL6K0gVhgBXuux6xQ+zsfK36tuG2NXhh+fAYM7y4=",
      "qxS0+1Nw3OIEcT7c2wZ6J/1yA4tSebUwfIQz8B0HpqU=",
    ],
    handlers: [],
    external: [],
  },
  "/views/filters.html": {
    inline: ["oc1Cu9AV6DsNQB03dr2sGFUzowFUkgUv0caw1PiNAHA="],
    handlers: [],
    external: [],
  },
  "/views/log.html": {
    inline: [
      "KE5Ab6aYYhONcsSwBMcBg6pAwt8VIAElyGK0Btc30e4=",
      "k+XHAEZyv1Zh8F7q0EinkkpKmik6CroFwm6oAKXfYmU=",
    ],
    handlers: [
      "4PpscOXIG8IgyUX5OvKLJNkRkd4nNKFk0GTFWY4hv10=",
      "9iYWtg8yF4SQNvjotu8O6gyQcq2HuphUWZ0PB6Y0G0E=",
      "w0rxKQf70pwOZAwTjQl37ee2UzlR73dJy5SJnNin4o4=",
    ],
    external: [],
  },
  "/views/logTabs.html": {
    inline: [],
    handlers: [],
    external: [],
  },
  "/views/preferences.html": {
    inline: [
      "EYGt3U/y2Ob0JCJH/oFKDHt2mOC4gCFfJo/24jDwcxc=",
      "jB8tnI20EcMp/OO6yy9aiuRb1/KpMUteKHWBRCWxGL4=",
    ],
    handlers: [
      "/CJCtEg7TRfR91mFOFu5Q9JzhQIVr8cv5gfcNr3uXVA=",
      "0LCzRoywkxhfj/VgkaMQS9WHcdaBYQlJ0nLlG5Xoltw=",
      "3dumb1qGN91W4evu+4I25ucm4B9DlkCQ5Mw6JQ0tQdU=",
      "4Tpw5f6TXSopWSkGx0mSuTu8AT6uQ4/zBEkhql+mG8M=",
      "57Lm5gWujNMS2HjS3WDF7MD3Htypt64a2ZjEuWbUYHc=",
      "8NzPS9W0773xgJwZ0ANs7ZVxCoIC74dZj8+zzuYbPQQ=",
      "9eSMVlOQu9rAPWblHO5ZItF7j+0hi1QuCgq6t3smvss=",
      "DKQ7OY7cH5JHFARWCI69YzD8ksl6zQ+67F279U9KYZs=",
      "DOa52SIedJ8u0DKxoNMUdLnir4wvt4qGUgFEWgDiNYs=",
      "Dt2md9F0gZwMoD1Til0r+uSY7cwqbIYTIiM0jhSCSLs=",
      "ET1rKXqBoJ4OjZPkW6oOjCTxwvU2sa/uTf1IsluzDCE=",
      "FOjeIvt2KPN1/irERh5f6Hp/cr14X6+UrAJLP74v23E=",
      "G12rOjYGpYzphWlkW0Y8lkMQAAkeAEnOUEuGMl8in1c=",
      "GYBbHebx/a2PVN4du/kBjO9uoQJoKZmKNRatz8LPSoY=",
      "L2Eyzbtcy3BHL7r8S9/FJaFSNisWtOEpXAvbziltN+Y=",
      "QzvlqumJFIu84ab8x7hgQ2hBN+hC51VIjnV5oku2vho=",
      "R8Pv2fawQKNKtuCdm7dJEm93d+AJUbcMTWLR9i2TeJE=",
      "SLV3ZI+7DH0/vGa+brUBZBsf/T4n36nMlA4Nfl4EX+Q=",
      "VpSydTEI78TVBM/+s2cutA98ukAadHY0Z4m7Y/ZtUIo=",
      "XNqgANw8jwnS5RKJ2gW+g8EoEdrPTeYg6qCC2e3QIwc=",
      "XWQXNXYzIf5KNwwJADr9mKZT2VzDTg1NEALMz8ls/x4=",
      "YK8LlkGGZFfxrE4ZoAM4gpsfyU29Bw59ImRPt2Ji2pc=",
      "aikSuQCqhvB2wWB5BPAFG1eiy6KtBA6ln+ylKESfQvc=",
      "cl8iMK1Pgpezro13JLk/NfSaX6SR4V8ubOuplFAKzUU=",
      "g00u3WwENKbyvCIgYoe6ZvfK9yG52iPvgpFn+IlecOo=",
      "hWMhwaxtbcnivzj7A+Q8/w2gOWDfD3wpMAIbtizd8xc=",
      "ju5ihWPl162+eba9uO5tUTrZOjU3lpo0a3t5F8EzQgE=",
      "kt/vm9z6lNoWS/pZY4m+op39DISJOzGUihKLFYbaAa8=",
      "lGVyx4xWsj4e07rQPExVpV33kFnu7AtLJBSUMqmukjA=",
      "m/XddpuaZGRAwwvDBL/iaLjvJrN7MMq9NxRgSS1aXRo=",
      "nyFEA6P3nr9QR8H3R3Xhp5CofcJAZw74UY+7pmmb/mA=",
      "q5We7qgqXjeS/snM4jSbyYwLfhN5UyC7y+BtXjJDrQo=",
      "suth41kjWOv3haw8GUkSPqXrhxytOgONRxohu6m8u1w=",
      "tUgma8jz8UvodwSjV0JdGAsj8Huz9o16FKHBb/bIf6A=",
      "tpooaa183vH8zmqOCFxxnYsW9Bk4+EgLDdtg0K1hhY8=",
      "uApzpsaTkOsiLVfHIpc01Mp4Em3ReVJ5Dp0uQFhRcc0=",
      "ueODhju532rJij04Pcx+6eio0276gvHq1ELunMp9tQc=",
      "vJXh0iwvvaxVta1u6smPRQ3kGwhGoa7Tdt0bXpjgzeE=",
      "xh8pY9r6q27aG01n7p0Qm/GcnUSdJw23xRflbIjkFTQ=",
      "zaj0Ft4ny61IqKiF3uEXXsZhM62QF0lvo00TAXHzpPQ=",
    ],
    external: [],
  },
  "/views/preferencesToolbar.html": {
    inline: ["iwOSGoD3VbRxOxlx+b55+ZJ8BSzx2n85v1b2Htk6f6U="],
    handlers: [],
    external: [],
  },
  "/views/properties.html": {
    inline: [],
    handlers: [],
    external: [],
  },
  "/views/propertiesToolbar.html": {
    inline: [],
    handlers: [],
    external: [],
  },
  "/views/rss.html": {
    inline: [
      "6W5D3+NI4Gb3hqbTQCG3TmN2OpDbmDOq08yb/jWQ9Uo=",
      "kNsHDUL+6kjawxQ/Gs7vMH+/+2NI1JHvhjrGTD45GLk=",
    ],
    handlers: [
      "/05/01Pv0fMmy5aIEYNkeYmdwR4CdFjIDeJMhjuW9F4=",
      "2Y6qtIMlA9tOk/1SbhvZi+w7OnHkL2W8sXYLr1WeO9s=",
      "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=",
      "PMszVPRdvwbjoRubf5u5FEPhFbWOR/cFkqaaHBnbGqk=",
      "jkde9ocyXOJ9KojbPJNPicrdFhe2ijLHzXGgQMiYgn4=",
    ],
    external: [],
  },
  "/views/rssDownloader.html": {
    inline: [
      "jncZ99qS4ZarnweUpumgeSPJN6veULjiWI8Js/Y7roA=",
      "ybTJ+bEAxgnsoFylb4TIabZ4h0NkdMYnLQn0k/pEzlM=",
    ],
    handlers: [
      "9orBLFJwthPTv47mjChsW8mibLtnF5YOooOeNmjwgag=",
      "HqytLDleX20lvQd/1cxVO0DIp8F1OQN1LOn3nKx5TIY=",
      "PtUT1Bal9M0CmRT6kYqLUsfiIp92Jx2D5TCKlL5D8sk=",
      "SA3qEmhJFBwDaUDXz06kbXdoAkG319mUxmh+xRaq/vE=",
    ],
    external: [],
  },
  "/views/statistics.html": {
    inline: [],
    handlers: [],
    external: [],
  },
  "/views/torrentcreator.html": {
    inline: [
      "RsgNCEPI93gZqjG0BxojC6ymHq9/ZENpU3aAdkT3zVw=",
      "Z2dePoztrKjqrOlihgEtB+VvIbj0sRlkyXBVxmkMU88=",
    ],
    handlers: [],
    external: [],
  },
  "/views/transferlist.html": {
    inline: ["YVm3tvhhVVhSR42Ax23RYflvCGayIM3EWbBjcpL+jVU="],
    handlers: [],
    external: [],
  },
};
