# SPDX-License-Identifier: AGPL-3.0-or-later

Classes = [
    {
        'cid': '{6ef418e4-ccad-4f98-8e1a-d4338dfd9d84}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=moz-searxng'],
        'esModule': 'resource:///modules/SearXNGProtocolHandler.sys.mjs',
        'constructor': 'SearXNGProtocolHandler',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'protocol_config': {
            'scheme': 'moz-searxng',
            'flags': [
                'URI_STD',
                'URI_DANGEROUS_TO_LOAD',
                'URI_IS_LOCAL_RESOURCE',
                'URI_IS_POTENTIALLY_TRUSTWORTHY',
                'URI_NON_PERSISTABLE',
                'URI_SCHEME_NOT_SELF_LINKABLE',
            ],
            'default_port': -1,
        },
    },
]
