# SPDX-License-Identifier: AGPL-3.0-or-later

Classes = [
    {
        'cid': '{6ef418e4-ccad-4f98-8e1a-d4338dfd9d84}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=searxng'],
        'esModule': 'resource:///modules/AboutSearXNG.sys.mjs',
        'constructor': 'AboutSearXNG',
    },
]
