#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later

import argparse
import base64
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_RE = re.compile(r"<script\b([^>]*)>(.*?)</script\s*>", re.IGNORECASE | re.DOTALL)
ATTRIBUTE_RE = re.compile(
    r"""\s+([^\s"'<>\/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?""",
    re.DOTALL,
)
TRANSLATION_RE = re.compile(
    r"QBT_TR\((([^)]|\)(?!QBT_TR))+)\)QBT_TR\[CONTEXT=([a-zA-Z_][a-zA-Z0-9_]*)\]"
)


def digest(value):
    return base64.b64encode(hashlib.sha256(value.encode()).digest()).decode()


def translated_english(value):
    return TRANSLATION_RE.sub(lambda match: match.group(1).replace('"', "&#34;"), value)


def canonical_script(value):
    return value.replace("${CACHEID}", "0")


def tags(source):
    cursor = 0
    while True:
        start = source.find("<", cursor)
        if start == -1:
            return
        quote = None
        for end in range(start + 1, len(source)):
            character = source[end]
            if quote:
                if character == quote:
                    quote = None
            elif character in "\"'":
                quote = character
            elif character == ">":
                yield source[start : end + 1]
                cursor = end + 1
                break
        else:
            return


def attributes(tag):
    result = {}
    for match in ATTRIBUTE_RE.finditer(tag):
        value = match.group(2) or match.group(3) or match.group(4) or ""
        result.setdefault(match.group(1).lower(), []).append(value)
    return result


def document_policy(path):
    source = path.read_text()
    inline = []
    external = []
    for match in SCRIPT_RE.finditer(source):
        script_attributes = attributes(match.group(1))
        if "src" in script_attributes:
            script_path = script_attributes["src"][0].split("?", 1)[0]
            external.append(
                script_path if script_path.startswith("/") else f"/{script_path}"
            )
        else:
            body = match.group(2)
            inline.extend((
                digest(canonical_script(body)),
                digest(canonical_script(translated_english(body))),
            ))
    handlers = []
    for tag in tags(source):
        if tag.startswith(("<!--", "</", "<!", "<?")):
            continue
        for name, values in attributes(tag).items():
            if name.startswith("on"):
                handlers.extend(digest(value) for value in values)
    return {
        "inline": sorted(set(inline)),
        "handlers": sorted(set(handlers)),
        "external": sorted(set(external)),
    }


def render_array(name, values):
    encoded = ", ".join(json.dumps(value) for value in values)
    compact = f"    {name}: [{encoded}],"
    if len(compact) <= 80:
        return [compact]
    return [
        f"    {name}: [",
        *(f"      {json.dumps(value)}," for value in values),
        "    ],",
    ]


def render(source_root):
    web_root = source_root / "src/webui/www"
    resource_file = web_root / "webui.qrc"
    resource_paths = sorted(
        set(
            re.findall(
                r"<file>private/([^<]+\.html)</file>",
                resource_file.read_text(),
            )
        )
    )
    lines = [
        "/* SPDX-License-Identifier: AGPL-3.0-or-later */",
        "",
        "// Generated by wildbuzzard/scripts/generate-torrent-document-sources.py.",
        "// Hashes cover pinned source and English fallback with CACHEID set to 0.",
        "export const TORRENT_DOCUMENT_SOURCES = {",
    ]
    for relative in resource_paths:
        lines.append(f"  {json.dumps('/' + relative)}: {{")
        policy = document_policy(web_root / "private" / relative)
        for name in ("inline", "handlers", "external"):
            lines.extend(render_array(name, policy[name]))
        lines.append("  },")
    lines.extend(("};", ""))
    return "\n".join(lines)


def patched_source(repository, temporary_root):
    qbt_root = repository / "wildbuzzard/third_party/gpl2/qbittorrent"
    source = temporary_root / "qbittorrent"
    shutil.copytree(qbt_root / "upstream", source)
    for patch_name in (qbt_root / "patches/series").read_text().splitlines():
        if not patch_name or patch_name.startswith("#"):
            continue
        with (qbt_root / "patches" / patch_name).open("rb") as patch_file:
            subprocess.run(
                [
                    "patch",
                    "--batch",
                    "--forward",
                    "--fuzz=0",
                    "-d",
                    source,
                    "-p1",
                ],
                check=True,
                stdin=patch_file,
                stdout=subprocess.DEVNULL,
            )
    return source


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    repository = Path(__file__).resolve().parents[2]
    with tempfile.TemporaryDirectory(prefix="wildbuzzard-qb-policy-") as temporary:
        source = args.source or patched_source(repository, Path(temporary))
        output = render(source)
    if args.check:
        if args.check.read_text() != output:
            print(f"{args.check} differs from the pinned qB WebUI", file=sys.stderr)
            return 1
    else:
        sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
