#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later

import argparse
import hashlib
import html
import importlib.util
import json
import os
import re
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[2]
BODY_PATH = (
    SOURCE_ROOT / "browser" / "base" / "content" / "overrides" / "app-license-body.html"
)
COPYRIGHT_PATH = SOURCE_ROOT / "wildbuzzard" / "packaging" / "copyright"


class ValidationError(Exception):
    pass


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def source_component(source_root, anchor, name, paths):
    files = []
    for relative in paths:
        contents = (source_root / relative).read_bytes()
        files.append({
            "sourcePath": relative,
            "installedPath": relative,
            "sha256": hashlib.sha256(contents).hexdigest(),
        })
    return {
        "anchor": anchor,
        "name": name,
        "path": name,
        "legalRoot": source_root,
        "inventory": {"packages": [{
            "name": name,
            "version": "",
            "license": "See original notices below",
            "licenseFiles": files,
        }]},
    }


def components(source_root):
    result = [source_component(source_root, "wildbuzzard-project-notices",
        "WildBuzzard and search plugin licences and source notices", [
            "LICENSE", "COPYING", "wildbuzzard/SOURCE-NOTICE",
            "wildbuzzard/BLOCKER-ASSET-SOURCE-NOTICE",
            "wildbuzzard/components/wildbuzzard-cli/NOTICE",
            "wildbuzzard/components/wildbuzzard-cli/MOZILLA-MCP-LICENSE",
            "wildbuzzard/browser/branding/LICENSE",
            "wildbuzzard/browser/extensions/web-search/extension/LICENSE",
            "wildbuzzard/browser/extensions/torrent-search/extension/LICENSE",
        ]), source_component(source_root, "wildbuzzard-spelling-notices",
        "English UK and US spelling dictionary notices", [
            "extensions/spellcheck/locales/en-US/hunspell/README_en_GB.txt",
            "extensions/spellcheck/locales/en-US/hunspell/README_en_US.txt",
            "extensions/spellcheck/locales/en-US/hunspell/en-GB.SOURCE.json",
        ])]
    for slug, name, path in [
        ("tor", "Tor third-party notices", "runtime/tor/tor"),
        ("torrent", "Torrent engine third-party notices", "runtime/torrent"),
    ]:
        legal_root = source_root / "wildbuzzard" / "third_party" / (slug + "-notices")
        result.append({
            "anchor": "wildbuzzard-" + slug + "-third-party",
            "name": name,
            "path": path,
            "inventory": json.loads((legal_root / "THIRD-PARTY.json").read_text()),
            "legalRoot": legal_root,
        })
    return result


def notice_documents(component):
    notices = {}
    for package in component["inventory"]["packages"]:
        for entry in package["licenseFiles"]:
            path = component["legalRoot"] / entry["installedPath"]
            contents = path.read_bytes()
            digest = hashlib.sha256(contents).hexdigest()
            if digest != entry["sha256"]:
                raise ValidationError(f"license digest mismatch: {path}")
            notice = notices.setdefault(
                digest,
                {
                    "contents": contents.decode("utf-8"),
                    "packages": set(),
                    "sourcePaths": set(),
                },
            )
            if notice["contents"].encode("utf-8") != contents:
                raise ValidationError(f"conflicting license digest: {path}")
            notice["packages"].add(f"{package['name']} {package['version']}".strip())
            notice["sourcePaths"].add(entry["sourcePath"])
    return notices


def declared_license(package):
    return package.get("license") or f"LicenseRef-{package['licenseFile']}"


def html_preformatted(contents):
    escaped = html.escape(contents, quote=False).splitlines()
    return "\n".join(
        "            " + re.sub(r"[ \t]+$", lambda match: "".join("&#32;" if char == " " else "&#9;" for char in match[0]), line).replace("\t", "&#9;") if line else ""
        for line in escaped
    )


def html_body(component_list):
    output = [
        "<!-- Generated by wildbuzzard/scripts/generate-third-party-notices.py. -->"
    ]
    for component in component_list:
        notices = notice_documents(component)
        output.extend([
            "<tr>",
            "  <td>",
            f'    <h1 id="{component["anchor"]}">{html.escape(component["name"])}</h1>',
            "  </td>",
            "  <td>",
            f"    <p>This notice applies to <code>{html.escape(component['path'])}</code> and the components identified below.</p>",
            "    <ul>",
        ])
        for package in component["inventory"]["packages"]:
            identity = f"{package['name']} {package['version']}".strip()
            output.append(
                "      <li><code>"
                + html.escape(identity)
                + "</code> — <code>"
                + html.escape(declared_license(package))
                + "</code></li>"
            )
        output.extend([
            "    </ul>",
            "  </td>",
            "  <td>",
            "    <p>Exact upstream legal files follow once per distinct SHA-256 digest. Package names identify every component that supplied each file.</p>",
        ])
        for digest, notice in sorted(notices.items()):
            packages = ", ".join(sorted(notice["packages"]))
            sources = ", ".join(sorted(notice["sourcePaths"]))
            output.extend([
                f'    <h2 id="{component["anchor"]}-{digest}">SHA-256 {digest}</h2>',
                f"    <p>Packages: {html.escape(packages)}<br>Upstream paths: <code>{html.escape(sources)}</code></p>",
                "    <pre>",
                html_preformatted(notice["contents"]),
                "    </pre>",
            ])
        output.extend(["  </td>", "</tr>"])
    return "\n".join(output) + "\n"


def text_body(component_list):
    output = [
        "WildBuzzard copyright and licensing notice",
        "============================================",
        "",
        "WildBuzzard-original code is licensed under AGPL-3.0-or-later. Mozilla,",
        "Waterfox, and other inherited code remains under its existing licenses.",
        "The complete general license texts are installed beside this file and are",
        "also available in the browser at about:license.",
        "",
    ]
    for component in component_list:
        notices = notice_documents(component)
        output.extend([component["name"], "-" * len(component["name"]), ""])
        output.append(f"Installed component: {component['path']}")
        output.append("")
        output.append("Packages:")
        for package in component["inventory"]["packages"]:
            output.append(
                f"  {package['name']} {package['version']} — {declared_license(package)}"
            )
        output.append("")
        output.append("Exact upstream legal files:")
        output.append("")
        for digest, notice in sorted(notices.items()):
            output.extend([
                f"SHA-256: {digest}",
                "Packages: " + ", ".join(sorted(notice["packages"])),
                "Upstream paths: " + ", ".join(sorted(notice["sourcePaths"])),
                "",
                notice["contents"].rstrip("\n"),
                "",
                "=" * 78,
                "",
            ])
    return "\n".join(line.rstrip() for line in "\n".join(output).splitlines()).rstrip() + "\n"


def output_documents(source_root):
    component_list = components(source_root)
    return {
        BODY_PATH: html_body(component_list).encode(),
        COPYRIGHT_PATH: text_body(component_list).encode(),
    }


def update(path, contents):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(contents)
    os.replace(temporary, path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        documents = output_documents(SOURCE_ROOT)
        for path, contents in documents.items():
            if arguments.check:
                if (
                    path.is_symlink()
                    or not path.is_file()
                    or path.read_bytes() != contents
                ):
                    raise ValidationError(
                        f"generated third-party notice is stale: {path}"
                    )
            else:
                update(path, contents)
    except (OSError, UnicodeError, json.JSONDecodeError, ValidationError) as error:
        raise SystemExit(str(error)) from error


if __name__ == "__main__":
    main()
