#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later

import argparse
import hashlib
import html
import importlib.util
import json
import os
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[2]
BODY_PATH = (
    SOURCE_ROOT
    / "browser"
    / "base"
    / "content"
    / "overrides"
    / "app-license-body.html"
)
COPYRIGHT_PATH = SOURCE_ROOT / "wildbuzzard" / "packaging" / "copyright"


class ValidationError(Exception):
    pass


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def components(source_root):
    scripts = source_root / "wildbuzzard" / "scripts"
    runner_module = load_module(
        "runner_crate_provenance", scripts / "runner_crate_provenance.py"
    )
    arti_module = load_module(
        "arti_crate_provenance", scripts / "arti_crate_provenance.py"
    )
    runner_root = (
        source_root / "wildbuzzard" / "components" / "wildbuzzard-cli" / "runner"
    )
    runner_legal = runner_root / "third_party"
    arti_legal = source_root / "wildbuzzard" / "third_party" / "arti-crates"
    try:
        runner = runner_module.validate_inventory(
            runner_root / "Cargo.lock",
            runner_legal / "THIRD-PARTY.json",
            runner_legal / "licenses",
        )
        arti = arti_module.validate_inventory(
            source_root / "third_party" / "arti" / "Cargo.lock",
            arti_legal / "THIRD-PARTY.json",
            arti_legal / "licenses",
            source_root / "wildbuzzard" / "third_party" / "arti.toml",
        )
    except (runner_module.ValidationError, arti_module.ValidationError) as error:
        raise ValidationError(str(error)) from error
    return (
        {
            "anchor": "wildbuzzard-arti-third-party",
            "name": "Arti third-party notices",
            "path": "runtime/tor/arti",
            "inventory": arti,
            "legalRoot": arti_legal,
        },
        {
            "anchor": "wildbuzzard-cli-third-party",
            "name": "WildBuzzard CLI third-party notices",
            "path": "/usr/bin/wildbuzzard",
            "inventory": runner,
            "legalRoot": runner_legal,
        },
    )


def notice_documents(component):
    notices = {}
    for package in component["inventory"]["packages"]:
        for entry in package["licenseFiles"]:
            path = component["legalRoot"] / entry["installedPath"]
            contents = path.read_bytes()
            digest = hashlib.sha256(contents).hexdigest()
            if digest != entry["sha256"]:
                raise ValidationError(f"license digest mismatch: {path}")
            notice = notices.setdefault(
                digest,
                {
                    "contents": contents.decode("utf-8"),
                    "packages": set(),
                    "sourcePaths": set(),
                },
            )
            if notice["contents"].encode("utf-8") != contents:
                raise ValidationError(f"conflicting license digest: {path}")
            notice["packages"].add(f"{package['name']} {package['version']}")
            notice["sourcePaths"].add(entry["sourcePath"])
    return notices


def declared_license(package):
    return package.get("license") or f"LicenseRef-{package['licenseFile']}"


def html_preformatted(contents):
    escaped = html.escape(contents, quote=False).splitlines()
    return "\n".join(f"            {line}" for line in escaped)


def html_body(component_list):
    output = [
        "<!-- Generated by wildbuzzard/scripts/generate-third-party-notices.py. -->"
    ]
    for component in component_list:
        notices = notice_documents(component)
        output.extend([
            "<tr>",
            "  <td>",
            f'    <h1 id="{component["anchor"]}">{html.escape(component["name"])}</h1>',
            "  </td>",
            "  <td>",
            f"    <p>This notice applies to <code>{html.escape(component['path'])}</code> and its statically linked Cargo dependencies.</p>",
            "    <ul>",
        ])
        for package in component["inventory"]["packages"]:
            identity = f"{package['name']} {package['version']}"
            output.append(
                "      <li><code>"
                + html.escape(identity)
                + "</code> — <code>"
                + html.escape(declared_license(package))
                + "</code></li>"
            )
        output.extend([
            "    </ul>",
            "  </td>",
            "  <td>",
            "    <p>Exact upstream legal files follow once per distinct SHA-256 digest. Package names identify every component that supplied each file.</p>",
        ])
        for digest, notice in sorted(notices.items()):
            packages = ", ".join(sorted(notice["packages"]))
            sources = ", ".join(sorted(notice["sourcePaths"]))
            output.extend([
                f'    <h2 id="{component["anchor"]}-{digest}">SHA-256 {digest}</h2>',
                f"    <p>Packages: {html.escape(packages)}<br>Upstream paths: <code>{html.escape(sources)}</code></p>",
                "    <pre>",
                html_preformatted(notice["contents"]),
                "    </pre>",
            ])
        output.extend(["  </td>", "</tr>"])
    return "\n".join(output) + "\n"


def text_body(component_list):
    output = [
        "WildBuzzard copyright and licensing notice",
        "============================================",
        "",
        "WildBuzzard-original code is licensed under AGPL-3.0-or-later. Mozilla,",
        "Waterfox, and other inherited code remains under its existing licenses.",
        "The complete general license texts are installed beside this file and are",
        "also available in the browser at about:license.",
        "",
    ]
    for component in component_list:
        notices = notice_documents(component)
        output.extend([component["name"], "-" * len(component["name"]), ""])
        output.append(f"Installed component: {component['path']}")
        output.append("")
        output.append("Packages:")
        for package in component["inventory"]["packages"]:
            output.append(
                f"  {package['name']} {package['version']} — {declared_license(package)}"
            )
        output.append("")
        output.append("Exact upstream legal files:")
        output.append("")
        for digest, notice in sorted(notices.items()):
            output.extend([
                f"SHA-256: {digest}",
                "Packages: " + ", ".join(sorted(notice["packages"])),
                "Upstream paths: " + ", ".join(sorted(notice["sourcePaths"])),
                "",
                notice["contents"].rstrip("\n"),
                "",
                "=" * 78,
                "",
            ])
    return "\n".join(output).rstrip() + "\n"


def output_documents(source_root):
    component_list = components(source_root)
    return {
        BODY_PATH: html_body(component_list).encode(),
        COPYRIGHT_PATH: text_body(component_list).encode(),
    }


def update(path, contents):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_bytes(contents)
    os.replace(temporary, path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        documents = output_documents(SOURCE_ROOT)
        for path, contents in documents.items():
            if arguments.check:
                if path.is_symlink() or not path.is_file() or path.read_bytes() != contents:
                    raise ValidationError(f"generated third-party notice is stale: {path}")
            else:
                update(path, contents)
    except (OSError, UnicodeError, json.JSONDecodeError, ValidationError) as error:
        raise SystemExit(str(error)) from error


if __name__ == "__main__":
    main()
