# SPDX-License-Identifier: AGPL-3.0-or-later

Classes = [
    {
        'cid': '{395d8425-b5fc-4d79-8f4c-dd83db4303dd}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=agent'],
        'esModule': 'resource:///modules/AboutAgent.sys.mjs',
        'constructor': 'AboutAgent',
    },
]
